name: "Backend tests"

on:
  workflow_call:

jobs:
  withplugins:
    name: with Plugins
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Install libreoffice
        uses: awalsh128/cache-apt-pkgs-action@v1.5.3
        with:
          packages: libreoffice libreoffice-pdfimport
          version: 1.0
      -
        name: Install etherpad core
        uses: actions/checkout@v3
        with:
          repository: ether/etherpad-lite
          path: etherpad-lite
      - uses: actions/setup-node@v6
        name: Install Node.js
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          package_json_file: ./etherpad-lite/package.json
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      -
        name: Checkout plugin repository
        uses: actions/checkout@v3
        with:
          path: plugin
      - name: Remove tests
        working-directory: ./etherpad-lite
        run: rm -rf ./src/tests/backend/specs
      -
        name: Install Etherpad core dependencies
        working-directory: ./etherpad-lite
        run: bin/installDeps.sh
      - name: Build Solr
        working-directory: ./plugin
        run: |
          docker buildx build -o type=docker -t ep_search/solr -f ./example/solr/Dockerfile ./example/solr
      - name: Install plugin
        working-directory: ./etherpad-lite
        run: |
          pnpm run plugins i --path ../../plugin
      -
        name: Run the backend tests
        working-directory: ./etherpad-lite/src
        run: |
          docker run -d --name etherpad-solr -p 8983:8983 ep_search/solr
          MAX_ATTEMPTS=60
          counter=0
          while ! nc -z localhost 8983; do
            echo "Waiting for Solr to start ${counter}/${MAX_ATTEMPTS}"
            counter=$((counter+1))
            if [ "$counter" -ge "$MAX_ATTEMPTS" ]; then
              echo "Solr did not start"
              exit 1
            fi
            sleep 0.5
          done
          counter=0
          while ! curl http://localhost:8983/solr/pad/admin/ping | grep '"status":"OK"'; do
            echo "Waiting for Solr to respond ${counter}/${MAX_ATTEMPTS}"
            counter=$((counter+1))
            if [ "$counter" -ge "$MAX_ATTEMPTS" ]; then
              echo "Solr did not respond"
              exit 1
            fi
            sleep 0.5
          done
          shopt -s globstar
          res=$(find ./plugin_packages -path "*/static/tests/backend/specs/*" 2>/dev/null | wc -l)
          if [ $res -eq 0 ]; then
            echo "No backend tests found"
            exit 1
          fi
          npx cross-env NODE_ENV=production mocha --import=tsx --timeout 120000 --recursive plugin_packages/ep_*/static/tests/backend/specs/** --settings ../plugin/tests/settings.json
        env:
          LOGLEVEL: DEBUG
      - name: Stop Solr
        if: always()
        run: |
          docker logs etherpad-solr
          docker stop etherpad-solr
          docker rm etherpad-solr
